global using MongoDB.Bson.Serialization.Attributes;
global using Database.Entities;
global using FluentValidation;
global using MongoDB.Entities;
global using MongoDB.Driver;
global using FastEndpoints;
global using MongoDB.Bson;
global using API.Auth;
global using API;
